export const LOGIN_LOADING = "LOGIN-LOADING"
export const LOGIN_SUCCESS = "LOGIN-SUCCESS"
export const LOGIN_FAIL= "LOGIN-FAIL"

export const LOGOUT = "LOG_OUT"

export const REGISTER_LOADING = "REGISTER_LOADING"
export const REGISTER_SUCCESS = "REGISTER_SUCCESS"
export const REGISTER_FAIL = "REGISTER_FAIL"

export const RESET = "RESET"
